### ISSUE TITLE
The option to add the credential is not visible.

### ISSUE THREAD

**Issue by PinkFloyd1213** [minhlucvan/n8n-nodes-browserless#10]
Hello,

When I add the node and try to add the credential to the Browserless instance, no option is shown. Similarly, if I search for the term "Browserless" on the credential page, nothing appears.

![image](https://github.com/minhlucvan/n8n-nodes-browserless/assets/31860086/bef5e2aa-0a66-4233-9998-df11e02c5e54)
![image](https://github.com/minhlucvan/n8n-nodes-browserless/assets/31860086/344a9e55-1bb2-4b6f-9fdb-e35407fde622)

I'm on the version 1.45.1 self-hosted of n8n. 

Do you have any idea why this is happening?

Thanks in advance.

**Comment by ddean6232** [comment]
Anything???

**Comment by PinkFloyd1213** [comment]
Yes, no way to add credentials..

**Comment by ddean6232** [comment]
I just started using just with the API..... Start browserlesss in a docker container and setup a data source on the apis

**Comment by ddean6232** [comment]
No need for this integration

**Comment by PinkFloyd1213** [comment]
Very strange. Before the API crendential didn't show up but now yes. 

Well, thanks for your help I guess. ;)
