### ISSUE TITLE
Bug: unable to add Browserless credentials

### ISSUE THREAD

**Issue by malfroid** [minhlucvan/n8n-nodes-browserless#11]
I am able to install the community node and add it to a workflow.

<img width="1204" alt="Screenshot 2024-07-17 at 13 56 07" src="https://github.com/user-attachments/assets/8f0b098d-0414-488a-993d-8bf5a796b3f5">

<img width="944" alt="Screenshot 2024-07-17 at 13 53 15" src="https://github.com/user-attachments/assets/97f77d4b-2289-4a6c-b2a7-fd9359bb0b3f">

However, when I try to add a credential to set the Browserless url and token, I do not have the option to select "Browserless":

<img width="941" alt="Screenshot 2024-07-17 at 13 52 54" src="https://github.com/user-attachments/assets/e9820570-379f-4f90-97aa-5ccb8637b4c4">

**Comment by minhlucvan** [comment]
New version of `n8n-nodes-browserless` has been released, let check it out to see if the issue had been fixed

https://www.npmjs.com/package/n8n-nodes-browserless/v/1.0.0

thank you!
