### ISSUE TITLE
Extracting CSS Elements

### ISSUE THREAD

**Issue by wifiuk** [minhlucvan/n8n-nodes-browserless#2]
When selecting Multiple Elements it currently appends them one after the other like this
![image](https://user-images.githubusercontent.com/3785545/213385406-1bdddf15-93e3-4010-b370-ce45504ffb07.png)

However, I'd like the ability (which I currently do in my handwritten puppeteer scripts) to have them side by side, such as
|| Element one || element two ||
|| element one output || element two output ||

Or have the ability to tell it what we want to be pulled back etc.
This way in n8n I can treat the same output as one item, not multiple items how it is being done now. If that makes sense.

**Comment by minhlucvan** [comment]
Thanks for reporting, gonna fix this asap

**Comment by minhlucvan** [comment]
I think that it would be better to use the default output., just disable the flattened output option
