### ISSUE TITLE
Click on element

### ISSUE THREAD

**Issue by xiNeRoar** [minhlucvan/n8n-nodes-browserless#6]
can we click on an html element and fill things in?

**Comment by minhlucvan** [comment]
Sure, you could execute Puppeteer script

**Comment by AlimFreight** [comment]
> Sure, you could execute Puppeteer script

Could you please help me figure out where I should put this script in browserless n8n node?

**Comment by minhlucvan** [comment]
New version of `n8n-nodes-browserless` has been released, let check it out to see if the issue had been fixed

https://www.npmjs.com/package/n8n-nodes-browserless/v/1.0.0

thank you!

**Comment by Lord-Shibe** [comment]
@AlimFreight hi, did you found out how to make click work?
