### ISSUE TITLE
Browserless v2 support

### ISSUE THREAD

**Issue by sdsys-ch** [minhlucvan/n8n-nodes-browserless#9]
Hey and thank you for this node.

Do you have plans to do a rewrite/ adaptation for browserless version 2?

Since['old browserless' might be gone by 2025](https://github.com/browserless/browserless/pull/3345) this would be amazing.

There are quite a few changes but adapting this node could be feasible without too much work?

I could offer looking into the joi schema changes for v2, if it helps.

Thanks!

**Comment by minhlucvan** [comment]
New version of `n8n-nodes-browserless` has been released, let check it out to see if the issue had been fixed

https://www.npmjs.com/package/n8n-nodes-browserless/v/1.0.0

thank you!
